title: Mega 的技術筆記
name: Mega
description: "這裡記錄了我的技術筆記與學習歷程，歡迎參考與分享"
url: "https://megaJingHua.github.io"
baseurl: ""
remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-include-cache
paginate: 10
markdown: kramdown
highlighter: rouge
author:
  name: "Mega"
  avatar: "/assets/images/avatar.png"
  bio: "前端 & 系統分析師，熱愛知識分享。"
  location: "Taiwan"
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/megaJingHua"
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:your@email.com"
