title: Mega 的技術筆記
name: Mega
description: "這裡記錄了我的技術筆記與學習歷程，歡迎參考與分享"
url: "https://megaJingHua.github.io"
baseurl: ""
remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-include-cache
paginate: 999
paginate_path: "/page:num"
markdown: kramdown
highlighter: rouge
author:
  name: "Mega"
  avatar: "/assets/images/avatar.png"
  bio: "前端 & 系統分析師，好奇心滿滿，熱愛分享與交流。"
  location: "Taiwan"
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/megaJingHua"
    - label: "Email"
      icon: "fas fa-envelope"
      url: "h12732u@gmail.com"
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true
