title: Mega 的部落格
name: Mega
description: "這是我的個人部落格，用 GitHub Pages 與 Minimal Mistakes 架設"
url: "https://megaJingHua.github.io"
baseurl: ""
theme: minimal-mistakes-jekyll
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-include-cache
paginate: 5
markdown: kramdown
